import tcod.constants

# Network related constants

GLOBAL_CHAT = "GLOBAL_CHAT"
SERVER = "SERVER"
LOBBIES = "LOBBIES"
MAP = "MAP"

PLAYER_INTENT = "PLAYER_INTENT"
PLAYER_RESOLVE = "PLAYER_RESOLVE"
PLAYER_CONNECT = "PLAYER_CONNECT"

# Game related constants

SCREEN_WIDTH = 128
SCREEN_HEIGHT = 72
GAME_TITLE = "Net Test"
FONT = 'assets/font_12x12.png'

FONT_OPTIONS_MASK = tcod.FONT_TYPE_GREYSCALE | tcod.FONT_LAYOUT_TCOD

# UI related constants

DEFAULT_MENU_WIDTH = 35
DEFAULT_MENU_HEIGHT = 10

DEFAULT_UI_FOREGROUND = (255, 255, 255)
SELECTED_UI_FOREGROUND = (245, 218, 66)
