import tcod.constants

# Network related constants

GLOBAL_CHAT = "GLOBAL_CHAT"
SERVER = "SERVER"
LOBBIES = "LOBBIES"
MAP = "MAP"

PLAYER_INTENT = "PLAYER_INTENT"
PLAYER_RESOLVE = "PLAYER_RESOLVE"
PLAYER_CONNECT = "PLAYER_CONNECT"

# Game related constants

# SCREEN_WIDTH = 128
# SCREEN_HEIGHT = 72


SCREEN_WIDTH = 120
SCREEN_HEIGHT = 68
GAME_TITLE = "Net Test"
FONT = 'assets/font_16x16w.png'

FONT_OPTIONS_MASK = tcod.FONT_TYPE_GREYSCALE | tcod.FONT_LAYOUT_TCOD

# UI related constants

DEFAULT_MENU_WIDTH = 35
DEFAULT_MENU_HEIGHT = 10

# Map Window

MAPWINDOW_WIDTH_RATIO = 0.7
MAPWINDOW_HEIGHT_RATIO = 0.6

MAPWINDOW_WIDTH = int(SCREEN_WIDTH * MAPWINDOW_WIDTH_RATIO)
MAPWINDOW_HEIGHT = int(SCREEN_HEIGHT * MAPWINDOW_HEIGHT_RATIO)

# Status Window

STATUSWINDOW_WIDTH_RATIO = 1 - MAPWINDOW_WIDTH_RATIO
STATUSWINDOW_HEIGHT_RATIO = 1

STATUSWINDOW_WIDTH = int(SCREEN_WIDTH * STATUSWINDOW_WIDTH_RATIO)
STATUSWINDOW_HEIGHT = int(SCREEN_HEIGHT * STATUSWINDOW_HEIGHT_RATIO)

# Chat Window

CHATWINDOW_WIDTH_RATIO = MAPWINDOW_WIDTH_RATIO
CHATWINDOW_HEIGHT_RATIO = 1 - MAPWINDOW_HEIGHT_RATIO

CHATWINDOW_WIDTH = int(SCREEN_WIDTH * CHATWINDOW_WIDTH_RATIO)
CHATWINDOW_HEIGHT = int(SCREEN_HEIGHT * CHATWINDOW_HEIGHT_RATIO)

CHATWINDOW_BACKGROUND_COLOR = (40, 40, 40)

ACTION_BAR_WIDTH_RATIO = MAPWINDOW_WIDTH_RATIO

ACTION_BAR_WIDTH = int(SCREEN_WIDTH * ACTION_BAR_WIDTH_RATIO)
ACTION_BAR_HEIGHT = 1

# COLOR DEFAULTS

DEFAULT_UI_FOREGROUND = (150, 150, 150)
DEFAULT_UI_BACKGROUND = (15, 15, 15)
SELECTED_UI_FOREGROUND = (245, 218, 66)
